//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: common_degree.proto
namespace Common
{
    [global::ProtoBuf.ProtoContract(Name=@"DegreeType")]
    public enum DegreeType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_INVALID", Value=0)]
      TYPE_INVALID = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_CHINESE", Value=1)]
      TYPE_CHINESE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_MATH", Value=2)]
      TYPE_MATH = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_ENGLISH", Value=3)]
      TYPE_ENGLISH = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_PHYSICS", Value=4)]
      TYPE_PHYSICS = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_GEOGRAPHY", Value=5)]
      TYPE_GEOGRAPHY = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_HISTORY", Value=6)]
      TYPE_HISTORY = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_BIOLOGY", Value=7)]
      TYPE_BIOLOGY = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_MUSIC", Value=8)]
      TYPE_MUSIC = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_SPORTS", Value=9)]
      TYPE_SPORTS = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_CHEMISTRY", Value=10)]
      TYPE_CHEMISTRY = 10
    }
  
}