//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: common_shop.proto
namespace Common
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaShop")]
  public partial class ArenaShop : global::ProtoBuf.IExtensible
  {
    public ArenaShop() {}
    
    private readonly global::System.Collections.Generic.List<Common.ArenaShop.Goods> _goods_list = new global::System.Collections.Generic.List<Common.ArenaShop.Goods>();
    [global::ProtoBuf.ProtoMember(1, Name=@"goods_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Common.ArenaShop.Goods> goods_list
    {
      get { return _goods_list; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Goods")]
  public partial class Goods : global::ProtoBuf.IExtensible
  {
    public Goods() {}
    

    private uint? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id?? default(uint); }
      set { _id = value; }
    }
    //Here has been deleted XmlIgnore
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return _id != null; }
      set { if (value == (_id== null)) _id = value ? id : (uint?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    

    private bool? _purchased;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"purchased", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool purchased
    {
      get { return _purchased?? default(bool); }
      set { _purchased = value; }
    }
    //Here has been deleted XmlIgnore
    [global::System.ComponentModel.Browsable(false)]
    public bool purchasedSpecified
    {
      get { return _purchased != null; }
      set { if (value == (_purchased== null)) _purchased = value ? purchased : (bool?)null; }
    }
    private bool ShouldSerializepurchased() { return purchasedSpecified; }
    private void Resetpurchased() { purchasedSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}