//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: common_scene.proto
namespace Common
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameRes")]
  public partial class GameRes : global::ProtoBuf.IExtensible
  {
    public GameRes() {}
    

    private Common.GameResType? _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Common.GameResType type
    {
      get { return _type?? Common.GameResType.GAME_RES_TYPE_INVALID; }
      set { _type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return _type != null; }
      set { if (value == (_type== null)) _type = value ? type : (Common.GameResType?)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    

    private string _des;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"des", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string des
    {
      get { return _des?? ""; }
      set { _des = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool desSpecified
    {
      get { return _des != null; }
      set { if (value == (_des== null)) _des = value ? des : (string)null; }
    }
    private bool ShouldSerializedes() { return desSpecified; }
    private void Resetdes() { desSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<long> _param_list = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(3, Name=@"param_list", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<long> param_list
    {
      get { return _param_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"SceneType")]
    public enum SceneType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_TYPE_INVALID", Value=0)]
      SCENE_TYPE_INVALID = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_TYPE_MAIN", Value=1)]
      SCENE_TYPE_MAIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_TYPE_COPY", Value=2)]
      SCENE_TYPE_COPY = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GameResType")]
    public enum GameResType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_TYPE_INVALID", Value=0)]
      GAME_RES_TYPE_INVALID = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_TYPE_COIN", Value=1)]
      GAME_RES_TYPE_COIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_TYPE_GOLD", Value=2)]
      GAME_RES_TYPE_GOLD = 2
    }
  
}