//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: command_user.proto
namespace Cmd.User
{
    [global::ProtoBuf.ProtoContract(Name=@"CMD")]
    public enum CMD
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_INVALID", Value=65535)]
      CMD_INVALID = 65535,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_BUY_ARENA_SHOP_GOODS_REQ", Value=10626)]
      CMD_BUY_ARENA_SHOP_GOODS_REQ = 10626,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_BUY_ARENA_SHOP_GOODS_RSP", Value=10627)]
      CMD_BUY_ARENA_SHOP_GOODS_RSP = 10627
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RET")]
    public enum RET
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RET_SYS_ERR", Value=-1)]
      RET_SYS_ERR = -1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RET_SUCCESS", Value=0)]
      RET_SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RET_MODULE_SWITCH_OFF", Value=256)]
      RET_MODULE_SWITCH_OFF = 256
    }
  
}