# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_SCENETYPE = descriptor.EnumDescriptor(
  name='SceneType',
  full_name='Common.SceneType',
  filename='SceneType',
  values=[
    descriptor.EnumValueDescriptor(
      name='SCENE_TYPE_INVALID', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SCENE_TYPE_MAIN', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SCENE_TYPE_COPY', index=2, number=2,
      options=None,
      type=None),
  ],
  options=None,
)


_GAMERESTYPE = descriptor.EnumDescriptor(
  name='GameResType',
  full_name='Common.GameResType',
  filename='GameResType',
  values=[
    descriptor.EnumValueDescriptor(
      name='GAME_RES_TYPE_INVALID', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_TYPE_COIN', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_TYPE_GOLD', index=2, number=2,
      options=None,
      type=None),
  ],
  options=None,
)


SCENE_TYPE_INVALID = 0
SCENE_TYPE_MAIN = 1
SCENE_TYPE_COPY = 2
GAME_RES_TYPE_INVALID = 0
GAME_RES_TYPE_COIN = 1
GAME_RES_TYPE_GOLD = 2



_GAMERES = descriptor.Descriptor(
  name='GameRes',
  full_name='Common.GameRes',
  filename='common_scene.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='Common.GameRes.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='des', full_name='Common.GameRes.des', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='param_list', full_name='Common.GameRes.param_list', index=2,
      number=3, type=18, cpp_type=2, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_GAMERES.fields_by_name['type'].enum_type = _GAMERESTYPE

class GameRes(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GAMERES

