# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_ENUMTEST = descriptor.EnumDescriptor(
  name='EnumTest',
  full_name='Common.EnumTest',
  filename='EnumTest',
  values=[
    descriptor.EnumValueDescriptor(
      name='ENUM_TEST_INVALID', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ENUM_TEST_A', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ENUM_TEST_B', index=2, number=2,
      options=None,
      type=None),
  ],
  options=None,
)


ENUM_TEST_INVALID = 0
ENUM_TEST_A = 1
ENUM_TEST_B = 2



_STRUCTTEST = descriptor.Descriptor(
  name='StructTest',
  full_name='Common.StructTest',
  filename='common_test.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='Common.StructTest.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='val', full_name='Common.StructTest.val', index=1,
      number=2, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_STRUCTTEST.fields_by_name['type'].enum_type = _ENUMTEST

class StructTest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STRUCTTEST

