# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_EFFECTTYPE = descriptor.EnumDescriptor(
  name='EffectType',
  full_name='Common.EffectType',
  filename='EffectType',
  values=[
    descriptor.EnumValueDescriptor(
      name='EFFECT_TYPE_INVALID', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EFFECT_TYPE_ABSOLUTE_MAX_HP', index=1, number=101,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EFFECT_TYPE_ABSOLUTE_CATK', index=2, number=102,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EFFECT_TYPE_ABSOLUTE_CDEF', index=3, number=103,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EFFECT_TYPE_ABSOLUTE_SATK', index=4, number=104,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EFFECT_TYPE_ABSOLUTE_SDEF', index=5, number=105,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EFFECT_TYPE_ABSOLUTE_CRIT', index=6, number=106,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EFFECT_TYPE_ABSOLUTE_DECRIT', index=7, number=107,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EFFECT_TYPE_ABSOLUTE_INCHURT', index=8, number=108,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EFFECT_TYPE_ABSOLUTE_INHURT', index=9, number=109,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EFFECT_TYPE_ABSOLUTE_DEHURT', index=10, number=110,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EFFECT_TYPE_ABSOLUTE_FORCE', index=11, number=111,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EFFECT_TYPE_ABSOLUTE_INTEL', index=12, number=112,
      options=None,
      type=None),
  ],
  options=None,
)


EFFECT_TYPE_INVALID = 0
EFFECT_TYPE_ABSOLUTE_MAX_HP = 101
EFFECT_TYPE_ABSOLUTE_CATK = 102
EFFECT_TYPE_ABSOLUTE_CDEF = 103
EFFECT_TYPE_ABSOLUTE_SATK = 104
EFFECT_TYPE_ABSOLUTE_SDEF = 105
EFFECT_TYPE_ABSOLUTE_CRIT = 106
EFFECT_TYPE_ABSOLUTE_DECRIT = 107
EFFECT_TYPE_ABSOLUTE_INCHURT = 108
EFFECT_TYPE_ABSOLUTE_INHURT = 109
EFFECT_TYPE_ABSOLUTE_DEHURT = 110
EFFECT_TYPE_ABSOLUTE_FORCE = 111
EFFECT_TYPE_ABSOLUTE_INTEL = 112



_EFFECT = descriptor.Descriptor(
  name='Effect',
  full_name='Common.Effect',
  filename='common_effect.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='Common.Effect.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='val', full_name='Common.Effect.val', index=1,
      number=2, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_EFFECT.fields_by_name['type'].enum_type = _EFFECTTYPE

class Effect(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EFFECT

