# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_ARENASHOP_GOODS = descriptor.Descriptor(
  name='Goods',
  full_name='Common.ArenaShop.Goods',
  filename='common_shop.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='Common.ArenaShop.Goods.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='purchased', full_name='Common.ArenaShop.Goods.purchased', index=1,
      number=2, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_ARENASHOP = descriptor.Descriptor(
  name='ArenaShop',
  full_name='Common.ArenaShop',
  filename='common_shop.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='goods_list', full_name='Common.ArenaShop.goods_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ARENASHOP.fields_by_name['goods_list'].message_type = _ARENASHOP_GOODS

class ArenaShop(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Goods(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ARENASHOP_GOODS
  DESCRIPTOR = _ARENASHOP

