//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: command_user_shop.proto
// Note: requires additional types generated from: common_shop.proto
namespace Cmd.User
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BUY_ARENA_SHOP_GOODS_REQ")]
  public partial class BUY_ARENA_SHOP_GOODS_REQ : global::ProtoBuf.IExtensible
  {
    public BUY_ARENA_SHOP_GOODS_REQ() {}
    

    private uint? _idx;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"idx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint idx
    {
      get { return _idx?? default(uint); }
      set { _idx = value; }
    }
    //Here has been deleted XmlIgnore
    [global::System.ComponentModel.Browsable(false)]
    public bool idxSpecified
    {
      get { return _idx != null; }
      set { if (value == (_idx== null)) _idx = value ? idx : (uint?)null; }
    }
    private bool ShouldSerializeidx() { return idxSpecified; }
    private void Resetidx() { idxSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BUY_ARENA_SHOP_GOODS_RSP")]
  public partial class BUY_ARENA_SHOP_GOODS_RSP : global::ProtoBuf.IExtensible
  {
    public BUY_ARENA_SHOP_GOODS_RSP() {}
    
    private readonly global::System.Collections.Generic.List<Common.ArenaShop.Goods> _goods_list = new global::System.Collections.Generic.List<Common.ArenaShop.Goods>();
    [global::ProtoBuf.ProtoMember(1, Name=@"goods_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Common.ArenaShop.Goods> goods_list
    {
      get { return _goods_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}